#!/usr/bin/env python3
"""Generate src/CourierTraits.sol from ../web/trait-tables.json.

The same JSON drives traits.js in the game, so the on-chain art and the 3D game
always agree on every courier's traits. Run after editing the tables:

    python3 tools/gen_traits.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
TABLES = json.loads((HERE.parent.parent / "web" / "trait-tables.json").read_text())
OUT = HERE.parent / "src" / "CourierTraits.sol"

rides = TABLES["rides"]
traits = TABLES["traits"]
assert sum(r["weight"] for r in rides) == 10_000, "ride weights must sum to 10,000"
for t in traits:
    assert sum(o[2] for o in t["options"]) == 100, f"{t['type']} weights must sum to 100"
    assert len(t["options"]) < 256


def const_name(s):
    return "".join(c if c.isalnum() else "_" for c in s.upper())


def sol_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = []
w = lines.append
w("// SPDX-License-Identifier: MIT")
w("pragma solidity ^0.8.26;")
w("")
w("// GENERATED by tools/gen_traits.py from trait-tables.json. Do not edit by hand.")
w("")
w("/// @title CourierTraits")
w("/// @notice Derives a courier's traits from keccak256(abi.encode(seed, id)), exactly")
w("///         like traits.js in the game: the ride from hash % 10,000, then each trait")
w("///         from its own 14-bit slice of the hash, starting at bit 16.")
w("library CourierTraits {")
w(f"    uint256 internal constant TRAIT_COUNT = {len(traits)};")
w("")
for i, t in enumerate(traits):
    w(f"    uint256 internal constant {const_name(t['type'])} = {i};")
w("")
# Style options get named constants so the SVG code can switch on them.
for t in traits:
    if not t["options"][0][1].startswith("#"):
        for j, o in enumerate(t["options"]):
            w(f"    uint8 internal constant {const_name(t['type'])}_{const_name(o[1])} = {j};")
w("")
w("    struct Traits {")
w("        uint8 ride;")
w(f"        uint8[{len(traits)}] opt;")
w("        uint16 heightPm; // body scale in per-mille, 920..1060")
w("    }")
w("")
w("    function derive(uint256 seed, uint256 id) internal pure returns (Traits memory t) {")
w("        uint256 h = uint256(keccak256(abi.encode(seed, id)));")
w("        t.ride = rideFrom(h % 10_000);")
w("        for (uint256 i = 0; i < TRAIT_COUNT; i++) {")
w("            t.opt[i] = _pick(_weights(i), ((h >> (16 + 14 * i)) & 0x3fff) % 100);")
w("        }")
w("        t.heightPm = uint16(920 + (((h >> 240) & 0xff) * 140) / 255);")
w("    }")
w("")
w("    function rideFrom(uint256 r) internal pure returns (uint8) {")
acc = 0
for k, r in enumerate(rides[:-1]):
    acc += r["weight"]
    w(f"        if (r < {acc}) return {k};")
w(f"        return {len(rides) - 1};")
w("    }")
w("")
w("    function _pick(bytes memory weights, uint256 r) private pure returns (uint8) {")
w("        for (uint256 j = 0; j < weights.length; j++) {")
w("            uint256 wj = uint8(weights[j]);")
w("            if (r < wj) return uint8(j);")
w("            r -= wj;")
w("        }")
w("        return uint8(weights.length - 1);")
w("    }")
w("")
w("    function _weights(uint256 trait) private pure returns (bytes memory) {")
for i, t in enumerate(traits):
    hexw = "".join(f"{o[2]:02x}" for o in t["options"])
    w(f"        if (trait == {i}) return hex\"{hexw}\";")
w("        revert();")
w("    }")
w("")
w("    /// @notice RGB colour of a colour trait's option, as 0xRRGGBB.")
w("    function colour(uint256 trait, uint256 opt) internal pure returns (uint24) {")
w("        bytes memory c;")
for i, t in enumerate(traits):
    if t["options"][0][1].startswith("#"):
        hexc = "".join(o[1][1:] for o in t["options"])
        w(f"        if (trait == {i}) c = hex\"{hexc}\";")
w("        return (uint24(uint8(c[opt * 3])) << 16) | (uint24(uint8(c[opt * 3 + 1])) << 8) | uint24(uint8(c[opt * 3 + 2]));")
w("    }")
w("")
w("    function typeName(uint256 trait) internal pure returns (string memory) {")
for i, t in enumerate(traits):
    w(f"        if (trait == {i}) return {sol_str(t['type'])};")
w("        return \"\";")
w("    }")
w("")
w("    function optionName(uint256 trait, uint256 opt) internal pure returns (string memory) {")
w("        string[] memory names;")
for i, t in enumerate(traits):
    w(f"        if (trait == {i}) {{")
    w(f"            names = new string[]({len(t['options'])});")
    for j, o in enumerate(t["options"]):
        w(f"            names[{j}] = {sol_str(o[0])};")
    w("        }")
w("        return names[opt];")
w("    }")
w("")
w("    function rideName(uint8 ride) internal pure returns (string memory) {")
for k, r in enumerate(rides):
    w(f"        if (ride == {k}) return {sol_str(r['name'])};")
w("        return \"\";")
w("    }")
w("")
w("    function rideRarity(uint8 ride) internal pure returns (string memory) {")
for k, r in enumerate(rides):
    w(f"        if (ride == {k}) return {sol_str(r['rarity'])};")
w("        return \"\";")
w("    }")
w("")
w("    function ridePower(uint8 ride) internal pure returns (uint256) {")
for k, r in enumerate(rides):
    w(f"        if (ride == {k}) return {r['power']};")
w("        return 0;")
w("    }")
w("}")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.relative_to(HERE.parent)}")
