// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// GENERATED by tools/gen_traits.py from trait-tables.json. Do not edit by hand.

/// @title CourierTraits
/// @notice Derives a courier's traits from keccak256(abi.encode(seed, id)), exactly
///         like traits.js in the game: the ride from hash % 10,000, then each trait
///         from its own 14-bit slice of the hash, starting at bit 16.
library CourierTraits {
    uint256 internal constant TRAIT_COUNT = 11;

    uint256 internal constant SKIN = 0;
    uint256 internal constant HAIR_COLOUR = 1;
    uint256 internal constant HAIRSTYLE = 2;
    uint256 internal constant HEADWEAR = 3;
    uint256 internal constant SHIRT = 4;
    uint256 internal constant ACCENT = 5;
    uint256 internal constant BOTTOMS = 6;
    uint256 internal constant BOTTOMS_COLOUR = 7;
    uint256 internal constant BAG = 8;
    uint256 internal constant SHOES = 9;
    uint256 internal constant BACKGROUND = 10;

    uint8 internal constant HAIRSTYLE_PONY = 0;
    uint8 internal constant HAIRSTYLE_BUN = 1;
    uint8 internal constant HAIRSTYLE_BOB = 2;
    uint8 internal constant HAIRSTYLE_TWIN = 3;
    uint8 internal constant HAIRSTYLE_LONG = 4;
    uint8 internal constant HEADWEAR_NONE = 0;
    uint8 internal constant HEADWEAR_CAP = 1;
    uint8 internal constant HEADWEAR_BUCKET = 2;
    uint8 internal constant HEADWEAR_BEANIE = 3;
    uint8 internal constant HEADWEAR_HEADPHONES = 4;
    uint8 internal constant HEADWEAR_GOGGLES = 5;
    uint8 internal constant BOTTOMS_SHORTS = 0;
    uint8 internal constant BOTTOMS_SKIRT = 1;
    uint8 internal constant BOTTOMS_PANTS = 2;
    uint8 internal constant BAG_SATCHEL = 0;
    uint8 internal constant BAG_BACKPACK = 1;
    uint8 internal constant BAG_TOTE = 2;
    uint8 internal constant BAG_SACK = 3;
    uint8 internal constant BAG_GOLDEN = 4;

    struct Traits {
        uint8 ride;
        uint8[11] opt;
        uint16 heightPm; // body scale in per-mille, 920..1060
    }

    function derive(uint256 seed, uint256 id) internal pure returns (Traits memory t) {
        uint256 h = uint256(keccak256(abi.encode(seed, id)));
        t.ride = rideFrom(h % 10_000);
        for (uint256 i = 0; i < TRAIT_COUNT; i++) {
            t.opt[i] = _pick(_weights(i), ((h >> (16 + 14 * i)) & 0x3fff) % 100);
        }
        t.heightPm = uint16(920 + (((h >> 240) & 0xff) * 140) / 255);
    }

    function rideFrom(uint256 r) internal pure returns (uint8) {
        if (r < 4500) return 0;
        if (r < 7000) return 1;
        if (r < 8700) return 2;
        if (r < 9600) return 3;
        return 4;
    }

    function _pick(bytes memory weights, uint256 r) private pure returns (uint8) {
        for (uint256 j = 0; j < weights.length; j++) {
            uint256 wj = uint8(weights[j]);
            if (r < wj) return uint8(j);
            r -= wj;
        }
        return uint8(weights.length - 1);
    }

    function _weights(uint256 trait) private pure returns (bytes memory) {
        if (trait == 0) return hex"121814100c0a";
        if (trait == 1) return hex"16140c0a0807060708";
        if (trait == 2) return hex"1812161014";
        if (trait == 3) return hex"1e180e0d0c07";
        if (trait == 4) return hex"140e0e0c0c0a0a08";
        if (trait == 5) return hex"16140e0e0c0a08";
        if (trait == 6) return hex"281e1e";
        if (trait == 7) return hex"1a14100c0c0e";
        if (trait == 8) return hex"2618101006";
        if (trait == 9) return hex"1e18140d0d";
        if (trait == 10) return hex"16100e10100a06";
        revert();
    }

    /// @notice RGB colour of a colour trait's option, as 0xRRGGBB.
    function colour(uint256 trait, uint256 opt) internal pure returns (uint24) {
        bytes memory c;
        if (trait == 0) c = hex"f6dcc8f3d2bbe8bfa0d9a47fb07a558a5a3c";
        if (trait == 1) c = hex"2a23265a3b2c8a3f2ac99a55c9c4bda48ac27cc2a8e08aa034476b";
        if (trait == 4) c = hex"f4efe09cc9e6f2c94ce9826fa8dcc4c4b3e034476b5e8c61";
        if (trait == 5) c = hex"2f8088d9534af2c94c3f6fbf5e9f578d5a99f08a2c";
        if (trait == 7) c = hex"34476b3b4145b59a6aa9514a6b7a455a7ea6";
        if (trait == 9) c = hex"2b2b2e6c5446f4f1ead9534a3f6fbf";
        if (trait == 10) c = hex"8fd2c9f6d2b8d6cdeef6e7a8bfe0f2f2c6cfc9dcb8";
        return (uint24(uint8(c[opt * 3])) << 16) | (uint24(uint8(c[opt * 3 + 1])) << 8) | uint24(uint8(c[opt * 3 + 2]));
    }

    function typeName(uint256 trait) internal pure returns (string memory) {
        if (trait == 0) return "Skin";
        if (trait == 1) return "Hair Colour";
        if (trait == 2) return "Hairstyle";
        if (trait == 3) return "Headwear";
        if (trait == 4) return "Shirt";
        if (trait == 5) return "Accent";
        if (trait == 6) return "Bottoms";
        if (trait == 7) return "Bottoms Colour";
        if (trait == 8) return "Bag";
        if (trait == 9) return "Shoes";
        if (trait == 10) return "Background";
        return "";
    }

    function optionName(uint256 trait, uint256 opt) internal pure returns (string memory) {
        string[] memory names;
        if (trait == 0) {
            names = new string[](6);
            names[0] = "Porcelain";
            names[1] = "Peach";
            names[2] = "Honey";
            names[3] = "Caramel";
            names[4] = "Cocoa";
            names[5] = "Umber";
        }
        if (trait == 1) {
            names = new string[](9);
            names[0] = "Ink";
            names[1] = "Chestnut";
            names[2] = "Auburn";
            names[3] = "Honey Blonde";
            names[4] = "Silver";
            names[5] = "Lilac";
            names[6] = "Mint";
            names[7] = "Rose";
            names[8] = "Midnight Blue";
        }
        if (trait == 2) {
            names = new string[](5);
            names[0] = "Ponytail";
            names[1] = "Bun";
            names[2] = "Bob";
            names[3] = "Twin Tails";
            names[4] = "Long";
        }
        if (trait == 3) {
            names = new string[](6);
            names[0] = "None";
            names[1] = "Courier Cap";
            names[2] = "Bucket Hat";
            names[3] = "Beanie";
            names[4] = "Headphones";
            names[5] = "Flight Goggles";
        }
        if (trait == 4) {
            names = new string[](8);
            names[0] = "Cream";
            names[1] = "Sky";
            names[2] = "Mustard";
            names[3] = "Coral";
            names[4] = "Mint";
            names[5] = "Lavender";
            names[6] = "Navy";
            names[7] = "Forest";
        }
        if (trait == 5) {
            names = new string[](7);
            names[0] = "Teal";
            names[1] = "Post Red";
            names[2] = "Sunflower";
            names[3] = "Cobalt";
            names[4] = "Leaf";
            names[5] = "Plum";
            names[6] = "Tangerine";
        }
        if (trait == 6) {
            names = new string[](3);
            names[0] = "Shorts";
            names[1] = "Skirt";
            names[2] = "Trousers";
        }
        if (trait == 7) {
            names = new string[](6);
            names[0] = "Navy";
            names[1] = "Charcoal";
            names[2] = "Khaki";
            names[3] = "Brick";
            names[4] = "Olive";
            names[5] = "Denim";
        }
        if (trait == 8) {
            names = new string[](5);
            names[0] = "Satchel";
            names[1] = "Backpack";
            names[2] = "Tote";
            names[3] = "Mail Sack";
            names[4] = "Golden Satchel";
        }
        if (trait == 9) {
            names = new string[](5);
            names[0] = "Black";
            names[1] = "Brown";
            names[2] = "White";
            names[3] = "Red";
            names[4] = "Blue";
        }
        if (trait == 10) {
            names = new string[](7);
            names[0] = "Teal";
            names[1] = "Peach";
            names[2] = "Lavender";
            names[3] = "Butter";
            names[4] = "Sky";
            names[5] = "Rose";
            names[6] = "Sage";
        }
        return names[opt];
    }

    function rideName(uint8 ride) internal pure returns (string memory) {
        if (ride == 0) return "On Foot";
        if (ride == 1) return "Skateboard";
        if (ride == 2) return "Bicycle";
        if (ride == 3) return "Moped";
        if (ride == 4) return "Paper Plane";
        return "";
    }

    function rideRarity(uint8 ride) internal pure returns (string memory) {
        if (ride == 0) return "Common";
        if (ride == 1) return "Uncommon";
        if (ride == 2) return "Rare";
        if (ride == 3) return "Epic";
        if (ride == 4) return "Legendary";
        return "";
    }

    function ridePower(uint8 ride) internal pure returns (uint256) {
        if (ride == 0) return 100;
        if (ride == 1) return 160;
        if (ride == 2) return 260;
        if (ride == 3) return 450;
        if (ride == 4) return 800;
        return 0;
    }
}
